#/* -------------------------------------------------------------------------- */
#/*                                GraphQL Types                               */
#/* -------------------------------------------------------------------------- */

type User {
    id: ID!
    name: String!
    email: String!
    message: String
}

#/* -------------------------------------------------------------------------- */
#/*                               GraphQL Queries                              */
#/* -------------------------------------------------------------------------- */

type Query {
    user(id: String): User
}

#/* -------------------------------------------------------------------------- */
#/*                              GraphQL Mutations                             */
#/* -------------------------------------------------------------------------- */

type Mutation {
    addUser(name: String!, email: String!): User
}
#/* -------------------------------------------------------------------------- */
#/*                            GraphQL Subscriptions                           */
#/* -------------------------------------------------------------------------- */
type Subscription {
    _: String
}
