#/* -------------------------------------------------------------------------- */
#/*                                GraphQL Types                               */
#/* -------------------------------------------------------------------------- */

type User {
    id: ID!
    name: String
    email: String
    message: String
    createdAt:String
    updatedAt:String
}

#/* -------------------------------------------------------------------------- */
#/*                               GraphQL Queries                              */
#/* -------------------------------------------------------------------------- */

type Query {
    users: [User]
    user(id: String): User
}

#/* -------------------------------------------------------------------------- */
#/*                              GraphQL Mutations                             */
#/* -------------------------------------------------------------------------- */

type Mutation {
    signUp(name: String!, email: String!, password: String!): User
}

#/* -------------------------------------------------------------------------- */
#/*                            GraphQL Subscriptions                           */
#/* -------------------------------------------------------------------------- */

type Subscription {
    _: String
}
